---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

# MMETSP

Read raw data.
```{r}
mmetsp_raw_data <- read_tsv('../data/sample-attr.tab.txt')
mmetsp_raw_data
```

Unpack attributes.
```{r}
mmetsp_wider <- mmetsp_raw_data %>%
  rename(sample_name_main = sample_name) %>%
  pivot_wider(id_cols = c('sample_id', 'sample_name_main'), names_from = "attr_type", values_from = "attr_value", names_repair = "unique")

mmetsp_wider
```
Select and unnest taxon info.
```{r}
mmetsp_taxon <- mmetsp_wider %>%
  select(sample_id, sample_name_main, taxon_id, phylum, class, order, genus, species, strain) %>%
  unnest() %>%
  mutate(
    genus_species_strain = gsub(" ", "_", paste(genus, species, strain, sep = "_"))
  )
mmetsp_taxon
```

Select only barebones.
```{r}
mmetsp_select <- mmetsp_taxon %>%
  select('sample_id', 'sample_name_main', 'taxon_id', 'genus_species_strain')
```

# Genbank

```{r}
colNames <- "assembly_accession, bioproject, biosample, wgs_master, refseq_category, taxid, species_taxid, organism_name, infraspecific_name, infraspecific_name2, isolateversion_status, assembly_level, release_type, genome_rep, seq_rel_date, asm_name, submitter, gbrs_paired_asm, paired_asm_comp, ftp_path, excluded_from_refseq, relation_to_type_material"
colNamesVec <- unlist(str_split(colNames, ", "))
```

```{r}
genbank <- read_tsv('../data/assembly_summary_genbank.txt',
                    comment = "#",
                    col_names = colNamesVec) %>%
  mutate(taxid = as.character(taxid),
         species_taxid = as.character(species_taxid))
```

```{r}
genbank_select <- genbank %>%
  select('taxid', 'species_taxid', 'organism_name', 'genome_rep', 'ftp_path')

genbank_select
```

# Join

```{r}
mmetsp_taxon
```

```{r}
genbank_select <- genbank_select %>%
  mutate(taxid = as.character(taxid),
         species_taxid = as.character(species_taxid))
genbank_select
```
```{r}
genbank
```

```{r}
suffix <- "_genomic.fna.gz"

join_taxid <- inner_join(mmetsp_taxon, genbank, by = c('taxon_id' = 'taxid')) %>%
  distinct(sample_id, .keep_all = TRUE) %>%
  distinct(taxon_id, .keep_all = TRUE) %>%
  rowwise() %>%
  mutate(
    genome_filename = paste(tail(str_split(ftp_path, '/')[[1]], 1), suffix, sep = ""),
    
    genome_ftp_path = paste(ftp_path, genome_filename, sep = "/")
  )
  
join_taxid
```
```{r}
write_csv(join_taxid, '../data/mmetsp_ncbi_genome_info.csv')
```


